### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by soumith** [yueatsprograms/Stochastic_Depth#1]
Hi, I came here after the paper pointed that this is where the code to reproduce the results lives. However, this repository does not seem to have it? There's only a few latex files.

**Comment by yueatsprograms** [comment]
Hi Soumith,

Sorry, I just put the code up this afternoon, see https://github.com/yueatsprograms/Stochastic_Depth/tree/master/code_cifar

This code trains on CIFAR-10 and CIFAR-100 and should get the results reported on Figure 3. I’m going to post a README tonight, and the code for SVHN and 1202-layer CIFAR (which requires some special memory optimization) will be up very soon.

Yu
