### ISSUE TITLE
Can you provide the multi-GPU version of your code

### ISSUE THREAD

**Issue by ruotianluo** [yueatsprograms/Stochastic_Depth#3]
I'm trying to train the 1202 layer network. I can't fit the network into one Titanx with batch size 128 (even with optnet).
I tried to use DataParallelTable as in fb.resnet.torch, however, due to some unknown reason, I can't make it work.
Can you provide your multi-GPU version of the code?

**Comment by yueatsprograms** [comment]
I don't have a multi-GPU version. The way we ran the 1202 layer network was by modifying the code in fb.resnet.torch.
